---
- name: Create directory for loopback files
  file:
    path: "{{ containerd_devmapper_image_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Create loopback backing files
  command:
    cmd: "truncate --size {{ item.size }} {{ containerd_devmapper_image_dir }}/{{ item.filename }}"
    creates: "{{ containerd_devmapper_image_dir }}/{{ item.filename }}"
  loop:
    - filename: data.img
      size: 100GiB
    - filename: metadata.img
      size: 10GiB

- name: Check loopback device status
  command:
    cmd: "losetup --associated {{ containerd_devmapper_image_dir }}/{{ item }}  --output NAME --noheadings"
  loop:
    - data.img
    - metadata.img
  register: existing_loopback_devices
  changed_when: false

- name: Create loopback devices
  command:
    cmd: "losetup --show --find {{ containerd_devmapper_image_dir }}/{{ item.item }}"
  when: item.stdout | length == 0
  loop: "{{ existing_loopback_devices.results }}"
  register: new_loopback_devices

# TODO use more idiomatic approach
- name: Register loopback device names
  set_fact:
    data_device: '
      {{
        new_loopback_devices.results[0]["stdout"] if "stdout" in new_loopback_devices.results[0] else
        new_loopback_devices.results[0]["item"]["stdout"]
      }}
    '
    metadata_device: '
      {{
        new_loopback_devices.results[1]["stdout"] if "stdout" in new_loopback_devices.results[1] else
        new_loopback_devices.results[1]["item"]["stdout"]
      }}
    '

- name: Get data device size
  command:
    cmd: "blockdev --getsize64 -q {{ data_device }}"
  changed_when: false
  register: data_device_size

- name: Create thinpool
  command:
    cmd: '
      dmsetup create {{ containerd_devmapper_pool_name }}
      --table "
        0
        {{ (data_device_size.stdout|int / containerd_devmapper_sector_size)|int }}
        thin-pool
        {{ metadata_device }}
        {{ data_device }}
        {{ containerd_devmapper_data_block_size }}
        {{ containerd_devmapper_low_water_mark }}
      "
    '
    creates: "/dev/mapper/{{ containerd_devmapper_pool_name }}"
