---
- name: Create directory for loopback files
  file:
    path: "{{ containerd_devmapper_image_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Create loopback backing files
  command:
    cmd: "truncate --size {{ item.size }} {{ containerd_devmapper_image_dir }}/{{ item.filename }}"
    creates: "{{ containerd_devmapper_image_dir }}/{{ item.filename }}"
  loop:
    # TODO move filenames to default variables
    - filename: data.img
      size: 100GiB
    - filename: metadata.img
      size: 10GiB

- name: Create loopback devices
  command:
    cmd: "losetup {{ item.device }} {{ containerd_devmapper_image_dir }}/{{ item.filename }}"
    creates: "{{ item.device }}"
  loop:
    - filename: data.img
      device: "{{ containerd_devmapper_data_device }}"
    - filename: metadata.img
      device: "{{ containerd_devmapper_metadata_device }}"

- name: Get data device size
  command:
    cmd: "blockdev --getsize64 -q {{ containerd_devmapper_data_device }}"
  changed_when: false
  register: data_device_size

- name: Create thinpool
  command:
    cmd: '
      dmsetup create {{ containerd_devmapper_pool_name }}
      --table "
        0
        {{ (data_device_size.stdout|int / containerd_devmapper_sector_size)|int }}
        thin-pool
        {{ containerd_devmapper_metadata_device }}
        {{ containerd_devmapper_data_device }}
        {{ containerd_devmapper_data_block_size }}
        {{ containerd_devmapper_low_water_mark }}
      "
    '
    creates: "/dev/mapper/{{ containerd_devmapper_pool_name }}"
