# Configure kernel modules for bridge traffic
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
---
- name: Configure required kernel modules
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf
    mode: 0755
    owner: root
    group: root
  notify: Reload configured kernel modules

- name: Force all notified handlers to run
  meta: flush_handlers

- name: Let iptables see bridged traffic
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-ip6tables
