---
- name: restart containerd
  service:
    name: containerd
    state: "{{ containerd_restart_handler_state }}"

- name: Enable setup-loopbacks service
  systemd:
    name: setup-loopbacks.service
    enabled: yes

- name: Reload configured kernel modules
  systemd:
    name: systemd-modules-load.service
    state: restarted
